name: Prisma migrate

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Prisma CLI
      run: yarn add -D prisma
    
    - name: Prisma generate
      run: yarn prisma generate
    
    - name: Run Prisma migrate
      run: yarn prisma migrate deploy